// src/components/rightDiv/Resume.svelte
<div class="bg-[#282828] p-4 rounded-lg flex items-center space-x-4 font-mono">
	<div
		class="flex-shrink-0 w-24 h-24 bg-gray-700 rounded-md overflow-hidden border border-gray-600"
	>
		<img
			src="https://res.cloudinary.com/dsegnno0z/image/upload/v1748272012/2025-05-26_20-36_t2m02f.png"
			alt="Resume Thumbnail"
			class="w-full h-full"
		/>
	</div>

	<div class="flex-grow">
		<p class="text-xl text-amber-300 font-bold tracking-wider">Resume</p>
		<a
			href="https://docs.google.com/document/d/1p1lM8qGFQbo8aEMi5lKIzpA1YzOJJNZKnpadHvKxsCc/edit?usp=sharing"
			target="_blank"
			class="text-sm text-gray-400 hover:text-amber-400 transition-colors duration-200 block mt-1"
		>
			Resume Link - updated Jul 25
		</a>
	</div>

	<a
		href="https://docs.google.com/document/d/1p1lM8qGFQbo8aEMi5lKIzpA1YzOJJNZKnpadHvKxsCc/edit?usp=sharing"
		target="_blank"
		class="flex-shrink-0 bg-black text-amber-300 px-6 py-2 rounded-full border border-amber-500 hover:bg-amber-600 hover:text-black transition-all duration-300 transform hover:scale-105 text-sm uppercase tracking-widest shadow-md"
	>
		Hire me
	</a>
</div>

// src/components/about/resume.tsx
import { Maximize2 } from "lucide-react"
import Link from "next/link"

export const Resume = () => {
  return <div className="h-full flex flex-col gap-5">
<Link
target="_blank"
  className="w-fit flex items-center gap-2 border border-neutral-200 text-neutral-600 p-2 px-6 rounded-lg text-sm"
  href="https://docs.google.com/document/d/1p1lM8qGFQbo8aEMi5lKIzpA1YzOJJNZKnpadHvKxsCc/edit?usp=sharing"
>
  <Maximize2 className="w-4 h-4" />
  View Full Screen
</Link>

  <div className="h-full px-4">
    <iframe className="w-full h-full" src="https://docs.google.com/document/d/e/2PACX-1vSJUigr1CQpYj5VoJ330Nafz5blrPrCM5taCypzjtU_CA7x-efdEfJAQQUhFL1G4dRIQbit5ocVnamT/pub?embedded=true"></iframe>
  </div>
  </div>
}
